---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: create vault group
  become: yes
  become_user: root
  group:
    name: '{{ vault_group }}'
    state: present

- name: create vault user
  become: yes
  become_user: root
  user:
    name: '{{ vault_user }}'
    group: '{{ vault_group }}'
    state: present

- name: create directories
  become: yes
  become_user: root
  with_items:
    - d: '{{ vault_config_dir }}'
    - d: '{{ vault_config_pki_dir }}'
  file:
    path: '{{ item.d }}'
    state: directory
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '{{ item.m | default("0700") }}'

- name: install keys/certs
  when: vault_config_tls is defined
  include_role:
    name: andrewrothstein.tls
  vars:
    tls_become: yes
    tls_become_user: root
    tls_src: '{{ vault_config_tls.pki_dir }}'
    tls_dest: '{{ vault_config_pki_dir }}'
    tls_dest_chown:
      owner: '{{ vault_user }}'
      grp: '{{ vault_group }}'

- name: install vault config...
  become: yes
  become_user: root
  with_items:
    - f: config.hcl
      d: '{{ vault_config_dir }}'
      m: '0644'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '{{ item.m }}'
  register: vault_config_modified

- include: '{{ vault_init | default("systemd") }}.yml'

- name: launch vault service
  become: yes
  become_user: root
  when: vault_activate
  service:
    name: vault
    enabled: true
    state: '{% if vault_config_modified.changed %}restarted{% else %}started{% endif %}'
