---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: make config dir...
  become: yes
  become_user: root
  file:
    path: '{{ vault_config_dir }}'
    state: directory
    mode: 0755

- name: install vault config...
  become: yes
  become_user: root
  with_items:
    - f: config.hcl
      d: '{{ vault_config_dir }}'
      m: '0644'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m }}'
