---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: create vault group
  become: yes
  become_user: root
  group:
    name: '{{ vault_group }}'
    state: present

- name: create vault user
  become: yes
  become_user: root
  user:
    name: '{{ vault_user }}'
    group: '{{ vault_group }}'
    state: present

- name: create directories
  become: yes
  become_user: root
  with_items:
    - d: '{{ vault_config_dir }}'
      m: '0700'
    - d: '{{ vault_config_pki_dir }}'
      m: '0700'
  file:
    path: '{{ item.d }}'
    state: directory
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '{{ item.m }}'

- name: install keys/certs
  when: vault_config_tls | default(False)
  include_role:
    name: andrewrothstein.tls
  vars:
    tls_src: '{{ vault_config_tls_src }}'
    tls_dest: '{{ vault_config_pki_dir }}'
    tls_dest_chown:
      owner: '{{ vault_user }}'
      grp: '{{ vault_group }}'

- name: install vault config...
  become: yes
  become_user: root
  with_items:
    - f: config.hcl
      d: '{{ vault_config_dir }}'
      m: '0644'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '{{ item.m }}'
